### ISSUE TITLE
Outdated gamedata for * Optimizations and runtime learning of

### ISSUE THREAD

**Issue by PLTAT** [dysphie/sm-map-translator#11]
L 05/31/2024 - 08:32:36: [map-translator.smx] Outdated gamedata for "CGameText::Display". Optimizations and runtime learning of 'game_text' is disabled. 
L 05/31/2024 - 08:32:36: [map-translator.smx] Outdated gamedata for "CPointMessageMultiplayer::SendMessage". Optimizations and runtime learning of 'point_message_multiplayer' is disabled.

**Comment by LevGitCode** [comment]
fix pls

**Comment by dysphie** [comment]
Fixed in 1.4.15
