### ISSUE TITLE
[Not works with outputs] game_text

### ISSUE THREAD

**Issue by MAGISTER-PD2OR** [dysphie/sm-map-translator#4]
Hello, not works when use AddOutput with game_text:
![Screenshot_33](https://user-images.githubusercontent.com/13406542/179265880-234231de-d667-48dc-b91e-2467c56d5f9f.jpg)

**Comment by dysphie** [comment]
Hi. There is support for this. You need to wait for the entity to display the new message, and then change level. 

![image](https://user-images.githubusercontent.com/11559683/179318558-12c6d5cd-bda5-408f-ba6e-7793f55b2e88.png)

Outputs:

```cpp
"Phrases"
{
	"422f99f1667215edbb8e61450f8a0591"
	{
		"en"		"default_text"
		"es"		"default_text"
		"ko"		"default_text"
	}
	"54061d40c105ee7d7287edf9de5a0239"
	{
		"en"		"changed_text"
		"es"		"changed_text"
		"ko"		"changed_text"
	}
}
```
