### ISSUE TITLE
sometimes objective messages are not translated

### ISSUE THREAD

**Issue by overmase** [dysphie/sm-map-translator#7]
NMRiH 1.13.1
OS : Windows
SourceMod Version: 1.11.0.6917

Error log: none

Cannot receive translated messages when joining a server later or when the player respawns but as the objective advances or updates I get the translated messages

case 1 : Play some translated map, players join later and check the objective message　(spectator mode)

case 2 : Play some translated map, Dead players respawn at checkpoints and check for objective messages

env_hudhint point_message_multiplayer is always translated

**Comment by dysphie** [comment]
Likely fixed in 1.3.13

**Comment by overmase** [comment]
Thank you
